#!/usr/bin/env python3
"""
Ingest USCIS I-485 (Application to Register Permanent Residence or Adjust
Status) field-office/service-center performance reports into the dashboard's
JSON dataset (data/i485_quarterly.json).

Usage:
    python3 scripts/ingest_i485.py data/raw/i485_performance_data_fy2026_q4_v1.xlsx [more files...]
    python3 scripts/ingest_i485.py --all          # re-ingest everything in data/raw/

Same USCIS report family as the N-400 ingestion (scripts/ingest_quarterly.py)
and built on the same shared parser (scripts/parse_common.py), but I-485's
layout has five category blocks per office instead of three: Family-based,
Employment-based, Humanitarian-based, Other, and Total (20 data columns,
not 12) -- see values_to_named_blocks in parse_common.py. Re-running this
script for a quarter already in the dataset overwrites that quarter in place.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from parse_common import (  # noqa: E402
    iter_grid_offices,
    load_grid,
    parse_fy_quarter_from_filename,
    quarter_dates,
    values_to_named_blocks,
)

REPO_ROOT = Path(__file__).resolve().parent.parent
RAW_DIR = REPO_ROOT / "data" / "raw"
OUTPUT_PATH = REPO_ROOT / "data" / "i485_quarterly.json"

NUM_VALUES = 20  # 5 category blocks x 4 fields (received/approved/denied/pending)
BUCKETS = ("family", "employment", "humanitarian", "other", "total")


def ingest_file(path: Path):
    fy, q = parse_fy_quarter_from_filename(path)
    quarter_key = f"FY{fy}Q{q}"
    start_date, end_date = quarter_dates(fy, q)

    offices = {}
    for rec in iter_grid_offices(load_grid(path), num_values=NUM_VALUES):
        code = rec["code"]
        if code is None:
            # Every I-485 quarter seen so far has a populated code column, unlike
            # N-400's FY2015 Q1; if a future quarter lacks one, this row is
            # silently dropped rather than guessed at -- surfaced via the office
            # count printed by main() being lower than expected.
            continue
        blocks, suppressed = values_to_named_blocks(rec["raw_values"], BUCKETS)
        offices[code] = {
            "code": code,
            "name": "All Offices (National)" if code == "TOTAL" else rec["name"].strip(),
            "state": rec["state"],
            "family": blocks["family"],
            "employment": blocks["employment"],
            "humanitarian": blocks["humanitarian"],
            "other": blocks["other"],
            "total": blocks["total"],
            "suppressed": suppressed,
        }

    return quarter_key, {
        "fy": fy,
        "quarter": q,
        "label": f"FY{fy} Q{q}",
        "periodStart": start_date,
        "periodEnd": end_date,
        "sourceFile": path.name,
        "sourceFormat": path.suffix.lstrip("."),
        "needsVerification": False,
        "offices": offices,
    }


def main(argv):
    if not argv:
        print(__doc__)
        return 1

    if argv == ["--all"]:
        paths = sorted(RAW_DIR.glob("i485_performance_data_*"))
    else:
        paths = [Path(a) for a in argv]

    if OUTPUT_PATH.exists():
        dataset = json.loads(OUTPUT_PATH.read_text())
    else:
        dataset = {"quarters": {}}

    for path in paths:
        if not path.exists():
            print(f"skip (not found): {path}", file=sys.stderr)
            continue
        quarter_key, quarter_data = ingest_file(path)
        dataset["quarters"][quarter_key] = quarter_data
        n_offices = len(quarter_data["offices"]) - 1
        print(f"ingested {path.name} -> {quarter_key} ({n_offices} offices/service centers)")

    ordered = dict(
        sorted(dataset["quarters"].items(), key=lambda kv: kv[1]["fy"] * 10 + kv[1]["quarter"])
    )
    dataset["quarters"] = ordered
    dataset["generatedNote"] = (
        "Generated by scripts/ingest_i485.py. Do not hand-edit; re-run the "
        "script against the source workbook(s) instead."
    )

    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(json.dumps(dataset, indent=2, sort_keys=False) + "\n")
    print(f"wrote {OUTPUT_PATH} ({len(dataset['quarters'])} quarters)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
